# Common configuration
service: task0

provider:
  name: aws
  runtime: python3.6
  stage: production
  region: eu-central-1

package:
  include:
    - common/**

# Serverless functions configuration
functions:
