# Common configuration
service: task1

provider:
  name: aws
  runtime: python3.6
  stage: production
  region: eu-central-1

package:
  include:
    - serverless_functions/**
    - common/**
  exclude:
    - monolith/**

# Serverless functions configuration
functions:
